### ISSUE TITLE
Changing one header cell changes all the header cells on the left 

### ISSUE THREAD

**Issue by alinastarkov** [plotly/dash-table#491] opened 2019-07-04 14:04 UTC
![bug2](https://user-images.githubusercontent.com/23650639/60672261-e778e200-9e42-11e9-8cc2-e8b046cefe3c.gif)

This only happened once when the cell is first changed.

**Comment by Marc-Andre-Rivet** [comment] 2019-07-09 19:22
The expected behavior here would be that since these headers are not merged, changing the value of a single header should only change that header!

Further more, if `rows` is changed to `foo`, all the header rows will be changed to `foo` with the current implementation because `rows` is a string, not an array in `column.name`. If `column.name` was `[rows, rows, rows]` it would change to `[rows, foo, rows]` when editing the 2nd header row for example.

**Changes required**
- modifying unmerged header cell affects only that cell, not other columns
- modifying unmerged header cell affects only that cell, not other rows
- merged behavior remains unchanged for columns
- merged behavior is consistent with unmerged behavior across rows

- [ ] unit tests for the behavior above on `dash-table/units/actions.js`
- [ ] a sanity integration test for the merged and unmerged behaviors

**Closed** 2019-07-16 17:25 UTC
Labels: Stage: In Progress, Type: Bug, size: 2
