### ISSUE TITLE
React Warning "each child should have a unique "key" prop

### ISSUE THREAD

**Issue by bjonen** [plotly/dash-table#860] opened 2020-12-22 09:52 UTC
When running the basic table example from https://dash.plotly.com/datatable, there is warning in the console: 

```
Warning: Each child in a list should have a unique "key" prop
```

I am running dash inside docker with versions: 
dash: 1.18.1
dash-table: 4.11.1

**Comment by xwk** [comment] 2021-06-08 06:42
Seems to be duplicate of https://github.com/plotly/dash/issues/1433

**Closed** 2021-09-30 05:23 UTC
