### ISSUE TITLE
Error selecting cell in virtualized table

### ISSUE THREAD

**Issue by kottmast** [plotly/dash-table#447] opened 2019-05-28 23:09 UTC
Clicking to select a cell that is "below the fold" throws: `TypeError: Cannot read property '1' of undefined`, where '1' is the column index of the cell that is clicked.

Simple example...

```python
dash_table.DataTable(
            id='table',
            data=df.to_dict('records'),
            columns=[{'id': c, 'name': c} for c in df.columns],
            editable=False,
            filtering=True,
            sorting=True,
            sorting_type="multi",
            pagination_mode=False,
            virtualization=True
)
```

When the data is loaded and the table is displayed, clicking a cell highlights that cell to indicate it is selected. If you then scroll down and click to select a new cell, the error is thrown. Full stack trace:

```
react-dom@16.8.6.min.js?v=0.24.0&m=1554834449:117 TypeError: Cannot read property '1' of undefined
    at e.value (type.ts:35)
    at e.value (type.ts:83)
    at data.ts:32
    at e.getDataEdges (memoizer.ts:7)
    at EdgeFactory.tsx:28
    at e.memoizedCreateEdges (memoizer.ts:7)
    at e.value (EdgeFactory.tsx:138)
    at index.tsx:18
    at t.value (index.tsx:458)
    at ce (react-dom@16.8.6.min.js?v=0.24.0&m=1554834449:98)
```

The property it tries to read appears to be the column index of the cell that was clicked, ie. if you click in the 5th column the error will be "Cannot read property '4' of undefined".

After that the table either disappears or becomes unresponsive. I discovered this while trying to add a callback to do something with the selected cells. There is no apparent server-side error and the callback executes successfully, so the error seems to happen after the callback is executed.

Versions:
dash 0.43.0
dash-table 3.7.0
Chrome 74.0

**Comment by kottmast** [comment] 2019-05-29 01:35
I just downgraded to dash_table==3.6.0 and do not see the error so it seems to be a regression introduced in 3.7.0.

**Comment by Marc-Andre-Rivet** [comment] 2019-05-29 15:27
@kottmast Thanks for reporting this. Investigating.

**Comment by vivekvs1** [comment] 2019-05-30 15:32
Having a similar error but for a different scenario. Assigning 'data' for a table based on selected_data of another table is throwing the same error. Like @kottmast has mentioned, it works fine when I downgraded to  dash_table==3.6.0

**Comment by wvwhome** [comment] 2019-06-19 17:20
Also error: ⛑️
Cannot read property '2' of undefined
with 3.7.0.  but I'm also using 'row_id' which is only in 3.7.0.  Stuck.

**Comment by Marc-Andre-Rivet** [comment] 2019-07-29 19:15
@kottmast @wvwhome I've reproduced this issue in `dash-table==3.7.0` by selecting a cell and arrowing down until 2 cells past the last visible cell. At that point the error you described occurs.

I've been unable to reproduce this example with `dash==1.0.2` (`dash-table==4.0.2`) - with the props having changed a bit, using:

```
import dash
import dash_table
import pandas as pd

app = dash.Dash(__name__)

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/Emissions%20Data.csv').reset_index()
df['Emission'] = df['Emission'].map(lambda x: '{0:.2f}'.format(x))

app.layout = dash_table.DataTable(
        id='table',
        data=df.to_dict('records'),
        columns=[{'id': c, 'name': c} for c in df.columns],
        editable=False,
        filter_action="native",
        sort_action="native",
        sort_mode="multi",
        page_action="none",
        virtualization=True
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

This seems to have been fixed by accident during the 3.x -> 4.0 refactoring.

Can you confirm that the behavior is ok on your side with the latest version? I've opened a follow up issue [here](https://github.com/plotly/dash-table/issues/520) to add a test for this scenarios.

**Comment by action-ghost** [comment] 2019-08-28 08:16
Can we using any solutions like “disable select action” to fix this？

**Comment by Marc-Andre-Rivet** [comment] 2019-08-29 15:37
Tests have been added to make sure this behavior does not break in the future (https://github.com/plotly/dash-table/pull/535).

Upgrading to `dash>=1.0.2` (`dash-table>=4.0.2`) should fix the issue.

@action-ghost What 3.7.0 feature do you use that is not available in 4.x?

The main issue raised in the 4.0 release was that we dropped the the hidden columns feature. That feature has been restructured into new props & UI, and is available again in 4.1 and above.

**Comment by Marc-Andre-Rivet** [comment] 2019-09-20 00:48
Closing as fixed and tested. There is way to alter the behavior in 3.7.0 in such a way as to avoid the error.

**Closed by Marc-Andre-Rivet** 2019-09-20 00:48 UTC
Labels: Meta: Regression, Type: Bug

**Comment by rp2532** [comment] 2020-01-10 19:49
I think this could be a related issue - 
https://github.com/plotly/dash-table/issues/436

**Comment by emilmajkowski** [comment] 2021-11-17 07:49
Hello,
It seems like the issue with "Cannot read properties of undefined (reading '')" when virtualization = True is back
dash-table 5.0.0
dash 2.0.0

Could you please review and fix?
