### ISSUE TITLE
selecting a dropdown alters row height

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-table#69] opened 2018-09-10 22:44 UTC
undesired behavior: selecting a dropdown increases the row height

**Comment by Marc-Andre-Rivet** [comment] 2019-01-29 16:43
@cldougl Table has changed a lot since September -- mind having another look and confirming if the issue still exists? I've made a few attempts but it looks like it's behaving fine.

**Comment by Marc-Andre-Rivet** [comment] 2019-09-05 18:21
Had another go at it. Unable to reproduce the issue. Closing. Please re-open if you can reproduce.

**Closed by Marc-Andre-Rivet** 2019-09-05 18:21 UTC
Labels: Type: Bug
