### ISSUE TITLE
datatable fail to expand horizontally after 4.0.0 upgrade

### ISSUE THREAD

**Issue by EBoisseauSierra** [plotly/dash-table#489] opened 2019-07-03 14:49 UTC
# Problem

When upgrading Dash to `v1.0.0` and Dash table (from `3.7.0`) to `4.0.0`, tables stop to auto-expand horizontally. In other words, they act as "`<span>`" instead of "`<p>`".

**with dash_table 3.7.0**
![Screenshot from 2019-07-03 15-31-56_shadow](https://user-images.githubusercontent.com/37387755/60600375-efd00f00-9da7-11e9-9f58-b4330034397b.png)

**with dash_table 4.0.0**
![Screenshot from 2019-07-03 15-33-16_shadow](https://user-images.githubusercontent.com/37387755/60600378-f2326900-9da7-11e9-9be8-9409584a907d.png)

The issue seems to come from the `<table>` HTML element. Indeed, its `<div class="cell cell-1-1 dash-fixed-content">` container expands to the full width of it's own parent. So if you manually set `width: 100%` to the `<table>` element, it works as expected.

However, it would be great to do this through the source code.
But, unlike what is detailed [here](https://dash.plot.ly/datatable/reference), the `css` attribute throws an error:
```
dash_table.DataTable(
    id='table',
    data=df.to_dict("rows"),
    columns=[{"name": i, "id": i} for i in df.columns],
    css={
        'width': '100%',
    },
),
```
and the `style_table` doesn't solve the issue:
```
dash_table.DataTable(
    id='table',
    data=df.to_dict("rows"),
    columns=[{"name": i, "id": i} for i in df.columns],
    style_table={
        'width': '100%',
    },
),
```

# Question(s)

Is it an expected behaviour?

If so, how to make table full (container's) width again? 

---
# MWE

## requirements for `dash_table` 3.7.0

```
dash-core-components==0.39.0
dash-html-components==0.13.2
dash-renderer==0.15.1
dash-table==3.7.0
dash==0.31.1
datetime
pandas==0.23.4
plotly==3.4.1
```

## requirements for `dash_table` 4.0.0

```
dash_renderer==1.0.0
dash-core-components==1.0.0
dash-html-components==1.0.0
dash-table==4.0.0
dash==1.0.0
pandas==0.24.2
plotly==3.10.0
```

## test app

```python
import dash
import dash_table
import dash_html_components as html
import pandas as pd

df = pd.read_csv(
    'https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv'
)

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        html.P(
            "foobar",
            style = {
                'background': 'cyan',
                'padding': '10px'
            }
        ),
        dash_table.DataTable(
            id='table',
            data=df.to_dict("rows"),
            columns=[{"name": i, "id": i} for i in df.columns],
        ),
    ],
    style = {
        'background': 'red',
        'padding': '10px'
    }
)


if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by chriddyp** [comment] 2019-07-05 12:13
If our default behaviour changed on this matter, we should also update the documentation.
![image](https://user-images.githubusercontent.com/1280389/60721665-96dab500-9f26-11e9-94ae-50606159fef8.png)

However, I believe that the previous 3.x default behaviour (expanding to the parent container's width) is the right behaviour here.

**Comment by EBoisseauSierra** [comment] 2019-07-07 09:44
Thanks for your answer. FYI, I've narrow down the issue to the [3.7.0 – 4.0.0] window.

**Comment by Marc-Andre-Rivet** [comment] 2019-07-10 15:37
Confirming this is caused by the `4.0.0` release. This behavior was driven by `content_style='grow'` vs. `content_style='fit'` which has been removed in `4.0.0`. Linked to https://github.com/plotly/dash-table/issues/176.

Testing out usage scenarios and will report back here.

**Comment by Marc-Andre-Rivet** [comment] 2019-07-10 20:12
Discussion notes: Need to verify if and how the default behavior has changed between 3.7.0 and 4.0.0 - reverting might be the best option. `grow` is probably the correct default. Rename the prop!

**Comment by bpostlethwaite** [comment] 2019-07-10 21:11
Cross posting a temporary fix for this for the people who end up here instead of https://community.plot.ly/t/how-to-make-datatable-has-width-100-after-4-0-0-upgrade/25145/6

adding this workaround as a `dash-table` property solved the issue for me as well as others
```python
css=[
    {
        'selector': 'table',
        'rule': 'width: 100%;'
    }
],
```

**Closed** 2019-07-15 17:22 UTC
Labels: Meta: Regression, Stage: In Review, Type: Bug, size: 2
