### ISSUE TITLE
Anyone has been able to use the pattern match id for the datatable?

### ISSUE THREAD

**Issue by xumiao** [plotly/dash-table#757] opened 2020-04-20 19:55 UTC
The latest Dash supports a pattern match id to work with the dynamic component loading. 

`id={'type': 'datatable', 'index': '234234'}`

However it does not seem to work with dash table for now. Any pointers?

Thanks.

**Comment by Marc-Andre-Rivet** [comment] 2020-04-20 20:31
@xumiao It's broken. The issue is described in more details here: https://github.com/plotly/dash/issues/1194

To be fixed in the next release.

**Comment by xumiao** [comment] 2020-04-20 22:49
@Marc-Andre-Rivet Thanks for the pointer.

**Closed** 2020-04-20 22:49 UTC
