### ISSUE TITLE
table up/down keys should hijack window scroll

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#15] opened 2018-06-05 19:15 UTC
![hijack](https://user-images.githubusercontent.com/1280389/40997587-3cc2ef36-68d3-11e8-9cd9-77f4f9b33b16.gif)

**Comment by Marc-Andre-Rivet** [comment] 2019-09-05 17:44
This seems fixed / unable to reproduce this behavior in `dash==1.2.0`, `dash-table==4.2.0`. Closing.

**Closed by Marc-Andre-Rivet** 2019-09-05 17:44 UTC
