### ISSUE TITLE
Hideable columns disappear after pasting data into table?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#611] opened 2019-10-02 17:21 UTC
as per https://community.plot.ly/t/hideable-columns-disappear-after-pasting-data-into-table/29342

i haven't attempted to reproduce this.

**Comment by alexcjohnson** [comment] 2019-10-02 17:35
possible duplicate of #576

**Comment by alexcjohnson** [comment] 2019-10-03 01:00
Still an existing bug, not a duplicate of #576, though I bet it's the same underlying issue repeated in a different part of the code.

- run the app below
- hide some columns
- paste new data into the table
- hidden columns are gone

```py
import dash
from dash_table import DataTable

app = dash.Dash(__name__)

app.layout = DataTable(
    columns=[{
        'name': x,
        'id': x,
        'hideable': True,
        'clearable': True,
        'deletable': True
    } for x in ['a', 'b', 'c', 'd']],
    editable=True,
    include_headers_on_copy_paste=True,  # or False, same bug
    data=[{
        'a': 'a' + str(x),
        'b': 'b' + str(x) + str(x),
        'c': 'c' + str(x) + 'c',
        'd': 'd' + str(x) + '-' + str(x)
    } for x in range(0, 100)]
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Closed** 2019-10-17 12:47 UTC
Labels: Stage: In Review, Type: Bug, size: 1
